require "rake/testtask"

Rake::TestTask.new(:spec) do |t|
  t.libs << "spec"
  t.libs << "lib"
  t.test_files = FileList["spec/**/*_spec.rb"]
end

task default: :spec

task :lines do
  rb_files = FileList["lib/**/*.rb"]
  puts %x(wc -l #{rb_files} | tail -1)
end
